CREATE TABLE IF NOT EXISTS users (
    username TEXT NOT NULL,
    pwhash BLOB NOT NULL,
    email TEXT NOT NULL PRIMARY KEY,
    salt BLOB NOT NULL,
    chat_color TEXT NOT NULL DEFAULT '#000000'
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (email) REFERENCES users(email)
);